version-tags: &version-tags
  tags:
    only: /v\d+\.\d+\.\d+/

version: 2.1
executors:
  my_container:
    docker:
      - image: cimg/python:3.11
        auth:
          username: jonathf
          password: $DOCKERHUB_PASSWORD

jobs:
  tests:
    executor: my_container
    steps:
      - checkout
      - run:
          name: "Installation"
          command: |
              python -m venv .venv
              source .venv/bin/activate
              pip install -U poetry PyYAML
              poetry install
      - run:
          name: "Smoke tests"
          command: |
              source .venv/bin/activate
              cv create --latex cvcreator/templates/example.toml output.tex
              cv aggregate test/aggregate_example.toml \
                cvcreator/templates/example.toml \
                cvcreator/templates/example.toml
              python -m cvcreator --latex cvcreator/templates/example.toml output.tex
      # - run:
      #     name: "Run tests"
      #     command: |
      #         source .venv/bin/activate
      #         pytest --doctest-modules cvcreator/
  deploy:
    executor: my_container
    steps:
      - checkout
      - run:
          name: "Build wheel"
          command: |
              python -m venv .venv
              source .venv/bin/activate
              poetry install
              pip install -U wheel
      - run:
          name: "Publish to PyPI"
          command: |
              source .venv/bin/activate
              poetry publish --build --username jonathf \
                  --password $PYPI_PASSWORD --no-interaction
workflows:
  version: 2
  workflow:
    jobs:
      - tests:
          filters:
            <<: *version-tags
      - deploy:
          requires:
            - tests
          filters:
            <<: *version-tags
            branches:
                ignore: /.*/
