version-tags: &version-tags
  tags:
    only: /v\d+\.\d+\.\d+/

version: 2
jobs:
  tests:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: "Installation"
          command: |
              pipenv install --deploy --dev
      - run:
          name: "Compile CV documents"
          command: |
              pipenv shell
              cvcreate examples/example.yaml --output output.tex --latex
      - run:
          name: "Run tests"
          command: |
              pipenv shell
              pytest --doctest-modules cvcreator/ test/
  deploy:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: "Build wheel"
          command: |
              pipenv install --deploy --dev
              pipenv shell
              python setup.py sdist bdist_wheel --universal
      - run:
          name: "Publish to PyPI"
          command: |
              pipenv shell
              twine upload --username jonathf --password $PYPI_PASSWORD dist/*
workflows:
  version: 2
  workflow:
    jobs:
      - tests:
          filters:
            <<: *version-tags
      - deploy:
          requires:
            - tests
          filters:
            <<: *version-tags
            branches:
                ignore: /.*/
