# Master list of available technical skills and associated group labels.

allowed_labels = [
  "Languages",
  "Tools",
  "Machine learning",
  "Mathematics",
  "Modelling",
  "Project management",
  "Scientific computing",
  "Build systems",
  "Cloud infrastructure",
  "Code interoperability",
  "Code management",
  "Databases",
  "Document generators",
  "Editors",
  "File formats",
  "Graphical toolkits",
  "Graphics",
  "Hardware",
  "Office suite",
  "Operating systems",
  "Package managers",
  "Parallelization",
  "Platforms",
  "Statistics",
  "Testing",
  "Version control",
  "Viritualization",
  "Visuallization",
  "Web tools",
]


# If we want to group some labels together.
[short_map]

"Bash" = "Shell"
"Fish" = "Shell"

"Microsoft SQL Server" = "SQL"
"MySQL" = "SQL"
"PostgreSQL" = "SQL"
"SQLAlchemy" = "SQL"
"SQLite" = "SQL"

"Amazon ECR" = "Amazon AWS"
"Amazon RDS" = "Amazon AWS"
"Amazon S3" = "Amazon AWS"
"Amazon VPC" = "Amazon AWS"
"Amazon CloudWatch" = "Amazon AWS"
"Amazon DynamoDB" = "Amazon AWS"
"Amazon Greengrass" = "Amazon AWS"

"OpenGL Shading Language" = "OpenGL"

"Azure Databricks" = "Microsoft Azure"
"Azure Devops" = "Microsoft Azure"

[skills]
"Akka" = ["Tools", "Web tools"]
"Alembic" = ["Tools", "Databases"]
"Amazon AWS" = ["Platforms", "Cloud infrastructure"]
"Amazon CloudWatch" = ["Platforms", "Cloud infrastructure"]
"Amazon DynamoDB" = ["Platforms", "Cloud infrastructure", "Databases"]
"Amazon ECR" = ["Platforms", "Cloud infrastructure"]
"Amazon Greengrass" = ["Hardware", "Platforms", "Cloud infrastructure"]
"Amazon RDS" = ["Platforms", "Cloud infrastructure", "Databases"]
"Amazon S3" = ["Platforms", "Cloud infrastructure"]
"Amazon VPC" = ["Platforms", "Cloud infrastructure"]
"Angular" = ["Tools", "Web tools"]
"Apache Spark" = ["Tools", "Databases"]
"Apple" = ["Platforms", "Operating systems"]
"Armadillo" = ["Tools", "Mathematics"]
"AsyncIO" = ["Tools", "Parallelization"]
"Autoconf" = ["Tools", "Code management", "Build systems"]
"Azure Databricks" = ["Platforms", "Cloud infrastructure"]
"Azure Devops" = ["Tools", "Testing"]
"Backbone.js" = ["Tools", "Web tools"]
"Bash" = ["Languages"]
"Black" = ["Tools", "Testing"]
"Blas" = ["Tools", "Mathematics"]
"Bokeh" = ["Tools", "Scientific computing", "Visuallization"]
"Boost" = ["Tools"]
"Boost.Python" = ["Tools", "Scientific computing"]
"C" = ["Languages"]
"C++" = ["Languages"]
"CLion" = ["Tools", "Editors"]
"CMake" = ["Tools", "Code management", "Build systems"]
"COMSOL" = ["Tools", "Scientific computing", "Modelling"]
"CSS" = ["Tools", "File formats", "Web tools"]
"CVS" = ["Tools", "Code management", "Version control"]
"C\\#" = ["Languages"]
"CircleCI" = ["Tools", "Testing"]
"Clojure" = ["Languages"]
"CodeCov" = ["Tools", "Testing"]
"Cognite-SDK" = ["Tools", "Scientific computing", "Modelling"]
"Confluence" = ["Tools", "Code management", "Project management"]
"Copper CRM" = ["Tools", "Office suite"]
"Cuda" = ["Tools", "Parallelization"]
"Cython" = ["Tools"]
"DOT" = ["Tools", "Graphics"]
"Dash" = ["Tools", "Scientific computing", "Machine learning"]
"Diffpack" = ["Tools", "Scientific computing", "Modelling"]
"Django" = ["Tools", "Web tools"]
"DocOnce" = ["Tools", "File formats"]
"Docker" = ["Platforms", "Cloud infrastructure"]
"Eclipse" = ["Tools", "Editors"]
"Eigen" = ["Tools", "Mathematics"]
"Elastic Search" = ["Tools", "Web tools"]
"Elixir" = ["Languages"]
"Emacs" = ["Tools", "Editors"]
"Erlang" = ["Languages"]
"FEniCS" = ["Tools", "Scientific computing", "Modelling"]
"FastAPI" = ["Tools", "Web tools"]
"Fish" = ["Languages"]
"Flask" = ["Tools", "Web tools"]
"Fortran" = ["Languages"]
"FreeSurfer" = ["Tools", "Scientific computing", "Modelling"]
"GCC" = ["Tools"]
"GDB" = ["Tools", "Testing"]
"GDL" = ["Languages"]
"GeoPandas" = ["Tools", "Scientific computing", "Modelling"]
"GMSH" = ["Tools", "Scientific computing", "Modelling"]
"GTK" = ["Tools", "Graphics", "Graphical toolkits"]
"Gimp" = ["Tools", "Graphics"]
"Git" = ["Tools", "Code management", "Version control"]
"Github" = ["Tools", "Code management", "Project management"]
"Go" = ["Languages"]
"GoogleTest" = ["Tools", "Testing", "Graphical toolkits"]
"Google Cloud Platform" = ["Platforms", "Cloud infrastructure"]
"Google OR-tools" = ["Tools", "Scientific computing", "Machine learning"]
"Grafana" = ["Tools", "Databases"]
"GraphQL" = ["Tools", "Web tools"]
"Graphviz" = ["Tools", "Scientific computing", "Visuallization"]
"Gromacs" = ["Tools", "Scientific computing", "Modelling"]
"Gtest" = ["Tools", "Testing"]
"H5py" = ["Tools", "File formats"]
"HDBSCAN" = ["Tools", "Scientific computing", "Machine learning"]
"HDF5" = ["Tools", "File formats"]
"HTML" = ["Tools", "File formats", "Web tools"]
"Heroku" = ["Platforms", "Cloud infrastructure"]
"Hugo" = ["Tools", "Web tools"]
"IDL" = ["Languages"]
"ImageAI" = ["Tools", "Scientific computing", "Machine learning"]
"Inkscape" = ["Tools", "Graphics"]
"IntelliJ" = ["Tools", "Editors"]
"Ipywidgets" = ["Tools", "Graphical toolkits"]
"JQuery" = ["Tools", "Web tools"]
"JUnit" = ["Tools", "Testing"]
"Java" = ["Languages"]
"Javascript" = ["Languages"]
"JetBrains" = ["Tools", "Editors"]
"Jira" = ["Tools", "Code management", "Project management"]
"Julia" = ["Languages"]
"Jupyter Notebook" = ["Tools", "Editors"]
"Keras" = ["Tools", "Scientific computing", "Machine learning"]
"Kotlin" = ["Languages"]
"Kubernetes" = ["Platforms", "Cloud infrastructure"]
"Lapack" = ["Tools", "Mathematics"]
"Linux" = ["Platforms", "Operating systems"]
"Lisp" = ["Languages"]
"Luascript" = ["Languages"]
"MPI" = ["Tools", "Parallelization"]
"Macaulay2" = ["Tools", "Scientific computing"]
"Make" = ["Tools", "Code management", "Build systems"]
"Markdown" = ["Tools", "File formats"]
"Mathematica" = ["Languages"]
"Matlab" = ["Languages"]
"Matplotlib" = ["Tools", "Scientific computing", "Visuallization"]
"Maven" = ["Tools", "Code management", "Build systems"]
"Mercurial" = ["Tools", "Code management", "Version control"]
"Microsoft Azure" = ["Platforms", "Cloud infrastructure"]
"Microsoft Excel" = ["Tools", "Office suite"]
"Microsoft Office Suite" = ["Tools", "Office suite"]
"Microsoft PowerBI" =  ["Tools"]
"Microsoft SQL Server" = ["Tools", "Databases"]
"Microsoft Windows" = ["Platforms", "Operating systems"]
"MySQL" = ["Tools", "Databases"]
"NLTK" = ["Tools", "Machine learning"]
"NPM" = ["Tools", "Code management", "Package managers"]
"Node.js" = ["Tools", "Web tools"]
"Numpy" = ["Tools", "Scientific computing"]
"OSG" = ["Tools", "Graphics"]
"Octave" = ["Languages"]
"OpenBSD" = ["Platforms", "Operating systems"]
"OpenCL" = ["Tools"]
"OpenCV" = ["Tools", "Scientific computing", "Machine learning"]
"OpenFOAM" = ["Tools", "Scientific computing", "Modelling"]
"OpenGL" = ["Tools", "Graphics", "Graphical toolkits"]
"OpenGL Shading Language" = ["Languages"]
"OpenMP" = ["Tools", "Parallelization"]
"OpenOffice" = ["Tools", "Office suite"]
"Openshift" = ["Platforms", "Cloud infrastructure"]
"PDB" = ["Tools", "Testing"]
"PETSc" = ["Tools", "Modelling"]
"PHP" = ["Languages"]
"Pandas" = ["Tools", "Scientific computing"]
"ParaView" = ["Tools", "Graphics"]
"Perl" = ["Languages"]
"Pip" = ["Tools", "Code management", "Package managers"]
"Plotly" = ["Tools", "Visuallization"]
"PostgreSQL" = ["Tools", "Databases"]
"PyCharm" = ["Tools", "Editors"]
"PyMC" = ["Tools", "Scientific computing", "Statistics"]
"PyPDF" = ["Tools", "Document generators"]
"Pybind11" = ["Tools", "Code interoperability"]
"Pylint" = ["Tools", "Testing"]
"Pytest" = ["Tools", "Testing"]
"Python" = ["Languages"]
"Pytorch" = ["Tools", "Scientific computing", "Machine learning"]
"Qlik" = ["Tools", "Graphics"]
"Qt" = ["Tools", "Graphics", "Graphical toolkits"]
"RStudio" = ["Tools", "Editors"]
"R" = ["Languages"]
"REST API" = ["Tools", "Web tools"]
"Racket" = ["Languages"]
"Raspberry Pi" = ["Hardware"]
"React" = ["Tools", "Web tools"]
"ReportLab" = ["Tools", "Document generators"]
"Restructured text" = ["Tools", "File formats"]
"Rust" = ["Languages"]
"SCons" = ["Tools", "Code management", "Build systems"]
"SegyIO" = ["Tools", "Modelling", "Scientific computing"]
"SLEPc" = ["Tools", "Mathematics"]
"SPARQL" = ["Tools", "Databases"]
"SQL" = ["Tools", "Databases"]
"SQLAlchemy" = ["Tools", "Databases"]
"SQLite" = ["Tools", "Databases"]
"STL" = ["Languages"]
"Scala" = ["Languages"]
"Scheme" = ["Languages"]
"Scikit-Learn" = ["Tools", "Scientific computing", "Machine learning"]
"Scipy" = ["Tools", "Scientific computing"]
"Seaborn" = ["Tools", "Scientific computing", "Visuallization"]
"Shapely" = ["Tools", "Modelling", "Scientific computing"]
"Shell" = ["Languages"]
"Sphinx" = ["Tools", "Document generators"]
"Splunk" = ["Platforms", "Cloud infrastructure"]
"Statsmodels" = ["Tools", "Scientific computing", "Statistics"]
"Subversion" = ["Tools", "Code management", "Version control"]
"SuperOffice" = ["Tools", "Office suite"]
"Swift" = ["Languages"]
"Swig" = ["Tools", "Code management", "Code interoperability"]
"Sympy" = ["Tools", "Scientific computing"]
"TKinter" = ["Tools", "Graphics", "Graphical toolkits"]
"Tcl/Tk" = ["Languages"]
"Tensorflow" = ["Tools", "Scientific computing", "Machine learning"]
"Three.js" = ["Tools", "Web tools"]
"TimescaleDB" = ["Tools", "Databases"]
"Tornado" = ["Tools", "Web tools"]
"Trello" = ["Tools", "Code management", "Project management"]
"Unittest" = ["Tools", "Testing"]
"Unix" = ["Platforms", "Operating systems"]
"VMD" = ["Tools", "Scientific computing", "Modelling"]
"VMWare" = ["Platforms", "Viritualization"]
"VTK" = ["Tools", "Graphics", "Graphical toolkits"]
"Valgrind" = ["Tools", "Testing"]
"Vim" = ["Tools", "Editors"]
"Vimscript" = ["Languages"]
"VirtualBox" = ["Platforms", "Viritualization"]
"Virtualenv" = ["Tools"]
"Vue.js" = ["Tools", "Web tools"]
"WebGL" = ["Tools", "Web tools", "Graphical toolkits"]
"XGBoost" = ["Tools", "Scientific computing", "Machine learning"]
"XML" = ["Tools", "File formats"]
"\\LaTeX" = ["Tools", "File formats"]
