name: Main

on:
   push:
     branches:
       - master
   pull_request:
     branches:    
       - master

jobs:
  test-and-build:
    uses: ./.github/workflows/test-and-build.yml

  release:
    needs: test-and-build
    if: ${{ needs.test-and-build.outputs.skip_release == 'NO' }}
    # if: ${{ github.ref == 'refs/heads/master' && needs.test-and-build.outputs.skip_release == 'NO' }}
    uses: ./.github/workflows/release.yml
    with:
      tag_name: ${{ needs.test-and-build.outputs.tag_name }}
