name: Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      tag_name:  ${{ inputs.tag_name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make a tag
        shell: bash
        run: git tag $tag_name

      - name: Download dist artifact 
        uses: actions/download-artifact@v3
        with:
          name: pkg-wheel

      # loads contents of the dist/ folder into PyPI
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: $tag_name
          release_name: Release $tag_name
          draft: false
          prerelease: false
    




