name: Release

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      wheel_file:
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      tag_name:  ${{ inputs.tag_name }}
      wheel_file:  ${{ inputs.wheel_file }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make a tag
        shell: bash
        run: |
          echo "Tag $tag_name" will be created
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git tag -a $tag_name -m "Updated by Github workflow"
          git push origin $tag_name

      - name: Download dist artifact 
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.wheel_file }}

      - name: Place artifacts
        shell: bash
        run: |
          mkdir dist/
          mv $wheel_file dist/$wheel_file

      # loads contents of the dist/ folder into PyPI
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: $tag_name
          release_name: Release $tag_name
          draft: false
          prerelease: false
    